// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int trials = Integer.parseInt(args[0]);
		int over = 0;
		int underequal = 0;

		for (int i = 0; i < trials; i++) {
			if (Math.random() > 0.5) {
				over++;
			} else {
				underequal++;
			}
		}

		if (underequal != 0) {
			double ratio = (double) over / underequal;
			System.out.println("> 0.5: " + over + " times");
			System.out.println("<= 0.5: " + underequal + " times");
			System.out.println("Ratio: " + ratio);
		} else {
			System.out.println("> 0.5: " + over + " times");
			System.out.println("<= 0.5: " + underequal + " times");
		}	
	}
}
